-- ============================================================================
-- UNIFLOW DATABASE SCHEMA CONFIGURATION
-- ============================================================================
-- Instructions:
-- 1. Go to your Supabase Project Dashboard (https://supabase.com).
-- 2. Open the 'SQL Editor' in the left-hand sidebar.
-- 3. Click 'New Query', paste this entire file's content, and click 'Run'.
-- 4. In the 'Storage' section in the sidebar, create a new private bucket 
--    named 'app-files' (do NOT toggle 'Public bucket' on).
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. Create Tables
-- ----------------------------------------------------------------------------

-- A. Profiles Table
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT,
    avatar_url TEXT,
    settings JSONB DEFAULT '{"theme": "light", "accentColor": "#5A5A40", "sidebarCollapsed": false}'::jsonb,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- B. Notes Table
CREATE TABLE IF NOT EXISTS public.notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    title TEXT DEFAULT 'Untitled Note',
    content TEXT DEFAULT '',
    folder TEXT DEFAULT 'General',
    cover_url TEXT,
    attachments JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- C. Todos Table
CREATE TABLE IF NOT EXISTS public.todos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    task TEXT NOT NULL,
    completed BOOLEAN DEFAULT FALSE,
    due_date TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- D. Budgets Table
CREATE TABLE IF NOT EXISTS public.budgets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    category TEXT NOT NULL,
    amount NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    type TEXT CHECK (type IN ('income', 'expense')) NOT NULL,
    date TIMESTAMPTZ DEFAULT NOW()
);

-- E. Reminders Table
CREATE TABLE IF NOT EXISTS public.reminders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    title TEXT NOT NULL,
    remind_at TIMESTAMPTZ NOT NULL,
    priority TEXT CHECK (priority IN ('High', 'Medium', 'Low')) DEFAULT 'Medium',
    completed BOOLEAN DEFAULT FALSE
);

-- ----------------------------------------------------------------------------
-- 2. Automatic Profile Trigger (PostgreSQL Trigger)
-- ----------------------------------------------------------------------------
-- This trigger automatically inserts a user profile row into the profiles 
-- table when a new user registers via Supabase email or Google OAuth signup.

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, name, avatar_url, settings)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'full_name', 'User'),
    COALESCE(new.raw_user_meta_data->>'avatar_url', new.raw_user_meta_data->>'picture'),
    '{"theme": "light", "accentColor": "#5A5A40", "sidebarCollapsed": false}'::jsonb
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Bind the trigger function to runs after every new auth.users insertion
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ----------------------------------------------------------------------------
-- 3. Enable Row Level Security (RLS)
-- ----------------------------------------------------------------------------
-- Standard security policies ensuring users can ONLY view/edit their own data.

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.todos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.budgets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reminders ENABLE ROW LEVEL SECURITY;

-- ----------------------------------------------------------------------------
-- 4. Define Security Policies
-- ----------------------------------------------------------------------------

-- A. Profiles Policies
CREATE POLICY "Allow users to read all profiles" 
  ON public.profiles FOR SELECT 
  USING (true);

CREATE POLICY "Allow users to update their own profile only" 
  ON public.profiles FOR UPDATE 
  USING (auth.uid() = id);

-- B. Notes Policies
CREATE POLICY "Allow individual read of own notes" 
  ON public.notes FOR SELECT 
  USING (auth.uid() = user_id);

CREATE POLICY "Allow individual insert of own notes" 
  ON public.notes FOR INSERT 
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Allow individual update of own notes" 
  ON public.notes FOR UPDATE 
  USING (auth.uid() = user_id);

CREATE POLICY "Allow individual delete of own notes" 
  ON public.notes FOR DELETE 
  USING (auth.uid() = user_id);

-- C. Todos Policies
CREATE POLICY "Allow individual read of own todos" 
  ON public.todos FOR SELECT 
  USING (auth.uid() = user_id);

CREATE POLICY "Allow individual insert of own todos" 
  ON public.todos FOR INSERT 
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Allow individual update of own todos" 
  ON public.todos FOR UPDATE 
  USING (auth.uid() = user_id);

CREATE POLICY "Allow individual delete of own todos" 
  ON public.todos FOR DELETE 
  USING (auth.uid() = user_id);

-- D. Budgets Policies
CREATE POLICY "Allow individual read of own budgets" 
  ON public.budgets FOR SELECT 
  USING (auth.uid() = user_id);

CREATE POLICY "Allow individual insert of own budgets" 
  ON public.budgets FOR INSERT 
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Allow individual delete of own budgets" 
  ON public.budgets FOR DELETE 
  USING (auth.uid() = user_id);

-- E. Reminders Policies
CREATE POLICY "Allow individual read of own reminders" 
  ON public.reminders FOR SELECT 
  USING (auth.uid() = user_id);

CREATE POLICY "Allow individual insert of own reminders" 
  ON public.reminders FOR INSERT 
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Allow individual update of own reminders" 
  ON public.reminders FOR UPDATE 
  USING (auth.uid() = user_id);

CREATE POLICY "Allow individual delete of own reminders" 
  ON public.reminders FOR DELETE 
  USING (auth.uid() = user_id);

-- ----------------------------------------------------------------------------
-- 5. Storage Security Rules for Bucket 'app-files'
-- ----------------------------------------------------------------------------
-- Optional but highly recommended:
-- To secure your storage assets so only logged-in users can upload and retrieve 
-- their own avatars, note cover photos, and attachments:
-- Copy the SQL below and run it if you wish to enforce bucket-level RLS policies,
-- or simply configure policies in your Supabase 'Storage' dashboard UI.

-- CREATE POLICY "Allow authenticated read on storage" 
--   ON storage.objects FOR SELECT 
--   USING (bucket_id = 'app-files' AND auth.role() = 'authenticated');

-- CREATE POLICY "Allow authenticated insert of own folder on storage" 
--   ON storage.objects FOR INSERT 
--   WITH CHECK (bucket_id = 'app-files' AND auth.role() = 'authenticated' AND (storage.foldername(name))[1] = auth.uid()::text);

-- CREATE POLICY "Allow authenticated delete of own folder on storage" 
--   ON storage.objects FOR DELETE 
--   USING (bucket_id = 'app-files' AND auth.role() = 'authenticated' AND (storage.foldername(name))[1] = auth.uid()::text);
